# Generated by Django 5.1.2 on 2024-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernet',
            name='phoneNumber',
            field=models.CharField(max_length=14),
        ),
    ]
